#!/bin/sh

# PROVIDE: JXCoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# JXCoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable JXCoin service.
# JXCoin_config (path): Set to /usr/local/etc/JXCoin.conf by default.
# JXCoin_user:  The user account JXCoin daemon runs as. It uses 'root' user by default.
# JXCoin_group: The group account JXCoin daemon runs as. It uses 'wheel' group by default.
# JXCoin_datadir (str): Default to "/var/db/JXCoin". Base data directory.

. /etc/rc.subr

name=JXCoin
rcvar=JXCoin_enable

: ${JXCoin_enable:=NO}
: ${JXCoin_config=/usr/local/etc/JXCoin.conf}
: ${JXCoin_datadir=/var/db/JXCoin}
: ${JXCoin_user="root"}
: ${JXCoin_group="wheel"}

required_files=${JXCoin_config}
command=/usr/local/bin/JXCoind
JXCoin_chdir=${JXCoin_datadir}
pidfile="${JXCoin_datadir}/JXCoind.pid"
stop_cmd=JXCoin_stop
command_args="-conf=${JXCoin_config} -datadir=${JXCoin_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

JXCoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${JXCoin_datadir}
	[ $? -eq 0 ] && chown -R ${JXCoin_user}:${JXCoin_group} ${JXCoin_datadir}
}

JXCoin_prestart()
{
	if [ ! -d "${JXCoin_datadir}/." ]; then
		JXCoin_create_datadir || return 1
	fi
}

JXCoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

JXCoin_stop()
{
    JXCoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${JXCoin_config} -datadir=${JXCoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
